---
id: 424d68d110
question: Error when running ImageDataGenerator.flow_from_dataframe
sort_order: 3980
---

Error: ImageDataGenerator name 'scipy' is not defined.

Check that scipy is installed in your environment.

Restart jupyter kernel and try again.

Marcos MJD

