---
course: mlops-zoomcamp
id: 982fa87351
question: 'Runtime Error : Failed to Reach API on Prefect'
section: 'Module 5: Monitoring'
sort_order: 2120
---

Problem: When to running evidently_metrics_calculation.py show RuntimeError: Cannot create flow run. Failed to reach API at [api.prefect.cloud](https://api.prefect.cloud/api/accounts/ee976605-4ca7-4a27-b5e3-0a37da3c7678/workspaces/78b23cf5-38bb-4d8b-9888-5bf8070d6d62/.)

Solution: Register or Signup on [https://app.prefect.cloud/account/](https://app.prefect.cloud/account/)

![Image](images/mlops-zoomcamp/image_f4090a89.png)

Added by Sofyan Akbar

